export const homepageActionTypes = {
    LOAD_HOME_SECTIONS_REQUEST: "LOAD_HOME_SECTIONS_REQUEST",
    LOAD_HOME_SECTIONS_SUCCESS: "LOAD_HOME_SECTIONS_SUCCESS",
    LOAD_HOME_SECTIONS_FAILURE: "LOAD_HOME_SECTIONS_FAILURE"
}