export const searchActionTypes = {
	FETCH_SEARCH_RESULTS_REQUEST: 'FETCH_SEARCH_RESULTS_REQUEST',
	FETCH_SEARCH_RESULTS_SUCCESS: 'FETCH_SEARCH_RESULTS_SUCCESS',
	FETCH_SEARCH_RESULTS_FAILURE: 'FETCH_SEARCH_RESULTS_FAILURE',
}