export const seriesActionTypes = {
    FETCH_NETFLIX_SERIES_REQUEST: 'FETCH_NETFLIX_SERIES_REQUEST',
    FETCH_NETFLIX_SERIES_SUCCESS: 'FETCH_NETFLIX_SERIES_SUCCESS',
    FETCH_NETFLIX_SERIES_FAILURE: 'FETCH_NETFLIX_SERIES_FAILURE',
}