export const moviesActionTypes = {
    FETCH_BANNER_DATA: 'FETCH_BANNER_DATA',
    FETCH_TOP_RATED: 'FETCH_TOP_RATED',
    FETCH_TRENDING: 'FETCH_TRENDING',
    FETCH_NETFLIX_ORIGINALS: 'FETCH_NETFLIX_ORIGINALS',
    FETCH_ACTION_MOVIES: 'FETCH_ACTION_MOVIES',
    FETCH_ADVENTURE_MOVIES: 'FETCH_ADVENTURE_MOVIES',
    FETCH_COMEDY_MOVIES: 'FETCH_COMEDY_MOVIES',
    FETCH_HORROR_MOVIES: 'FETCH_HORROR_MOVIES',
    FETCH_ROMANCE_MOVIES: 'FETCH_ROMANCE_MOVIES',
    FETCH_ANIMATION_MOVIES: 'FETCH_ANIMATION_MOVIES'
}