export const moviesActionTypes = {
    FETCH_COMEDY_MOVIES_REQUEST: 'FETCH_COMEDY_MOVIES_REQUEST',
    FETCH_COMEDY_MOVIES_SUCCESS: 'FETCH_COMEDY_MOVIES_SUCCESS',
    FETCH_COMEDY_MOVIES_FAILURE: 'FETCH_COMEDY_MOVIES_FAILURE',
    LOAD_MORE_COMEDY_MOVIES_SUCCESS: 'LOAD_MORE_COMEDY_MOVIES_SUCCESS',

    FETCH_BANNER_MOVIES_REQUEST: 'FETCH_BANNER_MOVIES_REQUEST',
    FETCH_BANNER_MOVIES_SUCCESS: 'FETCH_BANNER_MOVIES_SUCCESS',
    FETCH_BANNER_MOVIES_FAILURE: 'FETCH_BANNER_MOVIES_FAILURE',
    LOAD_MORE_BANNER_MOVIES_SUCCESS: 'LOAD_MORE_BANNER_MOVIES_SUCCESS',

    FETCH_FEATURED_MOVIES_REQUEST: 'FETCH_FEATURED_MOVIES_REQUEST',
    FETCH_FEATURED_MOVIES_SUCCESS: 'FETCH_FEATURED_MOVIES_SUCCESS',
    FETCH_FEATURED_MOVIES_FAILURE: 'FETCH_FEATURED_MOVIES_FAILURE',
    LOAD_MORE_FEATURED_MOVIES_SUCCESS: 'LOAD_MORE_FEATURED_MOVIES_SUCCESS',

    FETCH_HORROR_MOVIES_REQUEST: 'FETCH_HORROR_MOVIES_REQUEST',
    FETCH_HORROR_MOVIES_SUCCESS: 'FETCH_HORROR_MOVIES_SUCCESS',
    FETCH_HORROR_MOVIES_FAILURE: 'FETCH_HORROR_MOVIES_FAILURE',
    LOAD_MORE_HORROR_MOVIES_SUCCESS: 'LOAD_MORE_HORROR_MOVIES_SUCCESS',
}